### ISSUE TITLE
SIGSEGV

### ISSUE THREAD

**Issue by maxsupermanhd** [dxing97/libdiscord#11]
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==11063==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fb052290206 bp 0x7fff77517f70 sp 0x7fff775176c8 T0)
==11063==The signal is caused by a READ memory access.
==11063==Hint: address points to the zero page.
    #0 0x7fb052290205  (/lib/x86_64-linux-gnu/libc.so.6+0x98205)
    #1 0x7fb052fd5c04 in strcat (/lib/x86_64-linux-gnu/libasan.so.5+0x39c04)
    #2 0x7fb052f934f3 in ld_headers2curl /root/discord/libdiscord/lib/REST.c:79
    #3 0x7fb052f93a38 in ld_rest_send_request /root/discord/libdiscord/lib/REST.c:236
    #4 0x7fb052f942d9 in ld_send_basic_message /root/discord/libdiscord/lib/REST.c:397
    #5 0x559c11e47d4b in callback /root/discord/main.c:273
    #6 0x7fb052f92ef1 in ld_gateway_dispatch_parser /root/discord/libdiscord/lib/libdiscord.c:1168
    #7 0x7fb052f92659 in ld_gateway_payload_parser /root/discord/libdiscord/lib/libdiscord.c:963
    #8 0x7fb052f91cba in ld_lws_callback /root/discord/libdiscord/lib/libdiscord.c:725
    #9 0x7fb051e97308 in lws_ws_client_rx_sm (/usr/local/lib/libwebsockets.so.14+0x1b308)
    #10 0x7fb051e964d6 in lws_ws_handshake_client (/usr/local/lib/libwebsockets.so.14+0x1a4d6)
    #11 0x7fb051e94147 in lws_read_h1 (/usr/local/lib/libwebsockets.so.14+0x18147)
    #12 0x7fb051e94e2b in rops_handle_POLLIN_ws (/usr/local/lib/libwebsockets.so.14+0x18e2b)
    #13 0x7fb051e90693 in lws_service_fd_tsi (/usr/local/lib/libwebsockets.so.14+0x14693)
    #14 0x7fb051ea8947 in _lws_plat_service_tsi.part.1 (/usr/local/lib/libwebsockets.so.14+0x2c947)
    #15 0x7fb051e907bc in lws_service (/usr/local/lib/libwebsockets.so.14+0x147bc)
    #16 0x7fb052f919ab in ld_service /root/discord/libdiscord/lib/libdiscord.c:604
    #17 0x559c11e4577c in main /root/discord/main.c:478
    #18 0x7fb05221c09a in __libc_start_main ../csu/libc-start.c:308
    #19 0x559c11e45aa9 in _start (/root/discord/main+0x6aa9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib/x86_64-linux-gnu/libc.so.6+0x98205) 
==11063==ABORTING
```

**Comment by maxsupermanhd** [comment]
Bump

**Comment by SpeedyCraftah** [comment]
rip

**Comment by ghost** [comment]
Compiling without AddressSanitizer fixes it for me

**Comment by maxsupermanhd** [comment]
> Compiling without AddressSanitizer fixes it for me

Did you run this on production? Try to leave this bot for a night online and see what happens...
